plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}

test {
    useJUnitPlatform()
}

application {
    mainClass.set('com.example.Main')
}

task buildJar(type: Jar) {
    from sourceSets.main.output
    archiveBaseName.set("my-application")
}
